# Generated by Django 4.1.5 on 2023-01-07 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_offer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="offer",
            name="code",
            field=models.TextField(max_length=10),
        ),
    ]
