# Generated by Django 4.1.5 on 2023-01-07 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_alter_offer_code"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="sock",
            new_name="stock",
        ),
    ]
