# Generated by Django 4.1.5 on 2023-01-07 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0004_rename_sock_product_stock"),
    ]

    operations = [
        migrations.AlterField(
            model_name="offer",
            name="code",
            field=models.CharField(max_length=10),
        ),
    ]
